### ISSUE TITLE
关于仓库中非master分支的疑问

### ISSUE THREAD

**Issue by wangshihetianya** [ch-Gao/The-way-to-job#16]
分支：`auto-update-contributors-1600696800649da1c65e`
这是github机器人吗？然后这个版本好像有点落后了hh，我看都离最新的master分支少了10多次commit
话说如果是机器人的话它为啥不记录最新的master分支？

**Comment by Junius8023** [comment]
![image](https://user-images.githubusercontent.com/70516150/93994267-474e0680-fdc2-11ea-8218-2507eaa0107e.png)
你说的那个是两天前的，提交数是15；还有一条昨天的分支，提交数是26。
机器人可能每晚10点提交一次pr，再创建一条新分支吧。

**Comment by wangshihetianya** [comment]
我看这机器人的这两个分支都已经被merge到master分支上了，应该可以删了吧？要不我给删了？

![2](https://user-images.githubusercontent.com/26179683/94091102-f550c380-fe49-11ea-8306-e5f67e47d52e.png)

然后这个新的gxc分支是咋弄得呀，是不是那个同学直接push上来了没有用PR

![1](https://user-images.githubusercontent.com/26179683/94091054-d4886e00-fe49-11ea-8544-f9bc5001ea0a.png)
![3](https://user-images.githubusercontent.com/26179683/94091517-fcc49c80-fe4a-11ea-8e8b-59a9f564c496.png)
